version: '3'

services:

  mongo-db:
    image: mongo:6.0
    container_name: auth-db
    restart: always
    ports:
      - 27017:27017
    volumes:
      - auth-db:/data/db

  auth-app:
    depends_on:
      - mongo-db
    container_name: auth-app
    env_file:
      - ./.env
    restart: always
    ports:
      - 3000:3000
    build: ./

volumes:
  auth-db:
    external: false